### ISSUE TITLE
Leftovers completion

### ISSUE THREAD

**Issue by CedricRobitaille** [CedricRobitaille/ecommerce-pattern-library#3]
As of now, all content required has been coded. Seen by visiting all pages.

@thomasjbradley

**Comment by thomasjbradley** [comment]
What did you add for the leftovers?

**Comment by CedricRobitaille** [comment]
I have created 2 cards to display content on the products page.

I put my forms inside 2 cards to be displayed on the signup page.

I have updated my ghost-btn to be better suited for my content.

And as of now, Those are all the leftovers I have to create/fix at this current time.

@thomasjbradley

**Comment by thomasjbradley** [comment]
:1st_place_medal:
