### ISSUE TITLE
Jekyll Generators completed.

### ISSUE THREAD

**Issue by CedricRobitaille** [CedricRobitaille/ecommerce-pattern-library#5]
Seen in the browse.html page.

@thomasjbradley

**Comment by thomasjbradley** [comment]
This is not complete. It isn’t using the product MD files to generate the page. The page has been created manually without the use of for-loops.

**Comment by CedricRobitaille** [comment]
@thomasjbradley 
I have since updated it. It should be good now.

Sorry for the error, I didn't quite understand the specifics of what was due.

**Comment by CedricRobitaille** [comment]
@thomasjbradley 

I have since updated the /products/search-1 page up to your specifications.

**Comment by thomasjbradley** [comment]
✅
