### ISSUE TITLE
Problem: Search Button same height as Search Bar.

### ISSUE THREAD

**Issue by CedricRobitaille** [CedricRobitaille/ecommerce-pattern-library#8]
I am having trouble getting the search button to be the exact same height as the search bar. It's always one or two pixels off the search bar. I've tried using changing heights with pixels, em, rem and have yet to make it match. Any ideas on how to fix it?

@thomasjbradley

**Comment by thomasjbradley** [comment]
Have you tried `height: 100%` on the `.search-button`?

**Comment by CedricRobitaille** [comment]
Thank you, it work perfectly.
